config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'projets' => 'projects#index', as: :projects
  get 'projets/:url' => 'projects#show', as: :project
  get 'agence' => 'agency#index', as: :agency

  namespace :admin do
    resources :projects
    resources :properties
    resources :users
    resources :categories
    resources :news
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :url, presence: true, uniqueness: true
  has_and_belongs_to_many :category
  has_and_belongs_to_many :property
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/1
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to admin_project_path(@project), notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to admin_project_path(@project), notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to admin_projects_url, notice: 'Project was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:url, :title, :summary, :content, :published)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find_by_url(params[:url])
    raise ActionController::RoutingError.new("Project #{params[:url]} does not exist") unless @project
  end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<%= form_for([:admin, @project]) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_project_path(@project) %> |
<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Title</th>
      <th>Summary</th>
      <th>Content</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.url %></td>
        <td><%= project.title %></td>
        <td><%= project.summary %></td>
        <td><%= project.content %></td>
        <td><%= project.published %></td>
        <td><%= link_to 'Show', admin_project_path(project) %></td>
        <td><%= link_to 'Edit', edit_admin_project_path(project) %></td>
        <td><%= link_to 'Destroy', admin_project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_admin_project_path %>

app/views/admin/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @project.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @project.summary %>
</p>

<p>
  <strong>Content:</strong>
  <%= @project.content %>
</p>

<p>
  <strong>Published:</strong>
  <%= @project.published %>
</p>

<%= link_to 'Edit', edit_admin_project_path(@project) %> |
<%= link_to 'Back', admin_projects_path %>