config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'projets' => 'projects#index', as: :projects
  get 'projets/:url' => 'projects#show', as: :project
  get 'agence' => 'agency#index', as: :agency

  namespace :admin do
    resources :projects
    resources :properties
    resources :users
    resources :categories
    resources :news
  end

end

app/models/property.rb
class Property < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :order, presence: true, uniqueness: true
  has_and_belongs_to_many :project
end

app/controllers/admin/properties_controller.rb
class Admin::PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  def index
    @properties = Property.all
  end

  # GET /properties/1
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  def create
    @property = Property.new(property_params)

    if @property.save
      redirect_to admin_property_path(@property), notice: 'Property was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /properties/1
  def update
    if @property.update(property_params)
      redirect_to admin_property_path(@property), notice: 'Property was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /properties/1
  def destroy
    @property.destroy
    redirect_to admin_properties_url, notice: 'Property was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def property_params
      params.require(:property).permit(:name, :order)
    end
end

app/helpers/admin/properties_helper.rb
module Admin::PropertiesHelper
end

app/views/admin/properties/_form.html.erb
<%= form_for([:admin, @property]) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :order %><br>
    <%= f.number_field :order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_property_path(@property) %> |
<%= link_to 'Back', admin_properties_path %>

app/views/admin/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Properties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.order %></td>
        <td><%= link_to 'Show', admin_property_path(property) %></td>
        <td><%= link_to 'Edit', edit_admin_property_path(property) %></td>
        <td><%= link_to 'Destroy', admin_property_path(property), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_admin_property_path %>

app/views/admin/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_properties_path %>

app/views/admin/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @property.name %>
</p>

<p>
  <strong>Order:</strong>
  <%= @property.order %>
</p>

<%= link_to 'Edit', edit_admin_property_path(@property) %> |
<%= link_to 'Back', admin_properties_path %>